# Generated by Django 5.2.3 on 2025-08-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appservicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(upload_to='media_servicios'),
        ),
    ]
